---
- name: Test Catalyst 8k Connection
  hosts: all
  gather_facts: no
  tasks:
    - name: update device hostname
      cisco.ios.ios_config:
        lines:
          - hostname test-devnet-switch111
    
    - name: verify if name change are there
      cisco.ios.ios_command:
        commands: show run | include hostname
      register: output

    - name: printer the show version output
      ansible.builtin.debug:
        var: output.stdout_lines

