---
- name: Test Catalyst 8k Connection
  hosts: all
  gather_facts: no
  tasks:
    - name: Get Device Facts
      cisco.ios.ios_facts:
      register: result

    - name: Show Version
      ansible.builtin.debug:
        var: result.ansible_facts.ansible_net_version
